language: go
go_import_path: github.com/rmescandon/cruder
go:        
  - 1.9

env:
  matrix:
    - TEST_SUITE="--static"
    - TEST_SUITE="--unit"

git:
  quiet: true

install:
  - echo $GOPATH
  - echo "Remaining install is done by the test script."
  - true

script:
  - sh -v ./run-checks $TEST_SUITE
