#!/bin/bash
if [ "$TRAVIS_BUILD_NUMBER" ]; then
    echo travis_fold:start:env
    printenv | sort
    echo travis_fold:end:env
fi

export LANG=C.UTF-8
export LANGUAGE=en
set -eu

if which goctest >/dev/null; then
    goctest="goctest"
else
    goctest="go test"
fi
COVERMODE=${COVERMODE:-atomic}
export GOPATH="${GOPATH:-$(realpath "$(dirname "$0")"/../../../../)}"
export PATH="$PATH:${GOPATH%%:*}/bin"

STATIC=
UNIT=

case "${1:-all}" in
    all)
        STATIC=1
        UNIT=1
        ;;
    --static)
        STATIC=1
        ;;
    --unit)
        UNIT=1
        ;;
    *)
        echo "Wrong flag ${1}. To run a single suite use --static or --unit"
        exit 1
esac

CURRENTTRAP="true"
EXIT_CODE=99
store_exit_code() {
    EXIT_CODE=$?
}
exit_with_exit_code() {
    exit $EXIT_CODE
}
addtrap() {
    CURRENTTRAP="$CURRENTTRAP ; $1"
    trap 'store_exit_code; $CURRENTTRAP ; exit_with_exit_code' EXIT
}

endmsg() {
    if [ $EXIT_CODE -eq 0 ]; then
        m="All good, what could possibly go wrong."
    else
        m="Crushing failure and despair."
    fi
    echo "$m"
}
addtrap endmsg


# Append the coverage profile of a package to the project coverage.
append_coverage() {
    profile="$1"
    if [ -f "$profile" ]; then
        grep -v "^mode:" -- "$profile" >> .coverage/coverage.out
        rm "$profile"
    fi
}

if [ ! -z "$STATIC" ]; then
    ./get-deps.sh

    echo Checking docs
    ./mdlint.py ./*.md

    echo Checking formatting
    fmt=""
    for dir in $(go list -f '{{.Dir}}' ./... | grep -v '/vendor/' ); do
        s="$(gofmt -s -l "$dir")"
        if [ -n "$s" ]; then
            fmt="$s\n$fmt"
        fi
    done

    if [ -n "$fmt" ]; then
        echo "Formatting wrong in following files"
        echo "$fmt"
        exit 1
    fi

    # go vet
    echo Running vet
    go list ./... | grep -v '/vendor/' | xargs go vet

    # golint
    echo Install golint
    if ! which golint >/dev/null; then
        go get github.com/golang/lint/golint
    fi
    
    echo Running lint
    for dir in $(go list -f '{{.Dir}}' ./... | grep -v '/vendor/' ); do
        lint="$(golint "$dir")"
        if [ -n "$lint" ]; then
            echo "Lint complains:"
            echo "$lint"
            exit 1
        fi
    done

    if which shellcheck >/dev/null; then
        echo Checking shell scripts...
        ( git ls-files -z 2>/dev/null ||
                find . \( -name .git -o -name cruder.launcher -o -name vendor \) -prune -o -print0 ) |
            xargs -0 file -N |
            grep -v cruder.launcher |
            awk -F": " '$2~/shell.script/{print $1}' |
            xargs shellcheck
    fi

    echo Checking spelling errors
    if ! which misspell >/dev/null; then
        go get -u github.com/client9/misspell/cmd/misspell
    fi
    for file in *; do
        if [ "$file" = "vendor" ]; then
            continue
        fi
        misspell -error -i auther "$file"
    done

    echo Checking for ineffective assignments
    if ! which ineffassign >/dev/null; then
        go get -u github.com/gordonklaus/ineffassign
    fi
    ineffassign .

    echo Checking for naked returns
    if ! which nakedret >/dev/null; then
        go get -u github.com/alexkohler/nakedret
    fi
    got=$(nakedret ./... 2>&1)
    if [ -n "$got" ]; then
        echo "$got"
        exit 1
    fi
fi

if [ ! -z "$UNIT" ]; then
    ./get-deps.sh

    # Prepare the coverage output profile.
    rm -rf .coverage
    mkdir .coverage
    echo "mode: $COVERMODE" > .coverage/coverage.out

    echo Building
    ./build.sh

    # tests
    echo Running tests from "$PWD"
    for pkg in $(go list ./... | grep -v '/vendor/' ); do
        go test -i "$pkg"
        $goctest -v -coverprofile=.coverage/profile.out -covermode="$COVERMODE" "$pkg"
        append_coverage .coverage/profile.out
    done
    
    # upload to codecov.io if on travis
    if [ "${TRAVIS_BUILD_NUMBER:-}" ]; then
        curl -s https://codecov.io/bash | bash /dev/stdin -f .coverage/coverage.out
    fi
fi

UNCLEAN="$(git status -s|grep '^??')" || true
if [ -n "$UNCLEAN" ]; then
    cat <<EOF

There are files left in the git tree after the tests:

$UNCLEAN
EOF
    exit 1
fi
